[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
#runner = "qemu-system-riscv64 -machine virt -smp 2 -nographic -serial mon:stdio -bios none -drive if=none,format=raw,file=hdd.img,id=barba_disk -device virtio-blk-device,drive=barba_disk -kernel "
runner = "qemu-system-riscv64 -machine virt -smp 2 -nographic -serial mon:stdio -bios none -drive if=none,format=raw,file=hdd.img,id=barba_disk -device virtio-blk-device,drive=barba_disk -device loader,file=./user/hello-newlib,addr=0x82000000,force-raw=true -kernel "
rustflags = ['-Clink-arg=-Tsrc/lds/riscv64gc.lds']

[target.armv7a-none-eabi]
runner = "qemu-system-arm -machine raspi2b -nographic -serial mon:stdio -dtb dtb/bcm2836-rpi-2-b.dtb -kernel "
rustflags = ['-Clink-arg=-Tsrc/lds/armv7a.lds']
